name: Build and Upload Artifact

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip source code
        run: zip -r artifact.zip .

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: latest-code
          path: artifact.zip
